### ISSUE TITLE
A class is created to represent an individual invoice

### ISSUE THREAD

**Issue by pmgreen** [pulibrary/lsp-data#23]
See https://developers.exlibrisgroup.com/alma/apis/docs/xsd/rest_invoice.xsd/ for the schema for an invoice.

Acceptance criteria:
- [x] An ApiInvoice class is made to represent the header information returned via an Invoice API call

**Comment by pmgreen** [comment]
Programmer: @mzelesky 
Reviewer: TBD

**Comment by mzelesky** [comment]
Closed by #24.
